// Seeded sample data for the "Try it free" demo.
// Reflects real ICP criteria (see PRD.md, Appendix A) — not a live data pull.

const SAMPLE_MATCHES = [
  { company: "Redline Structural Group", territory: "New York", industry: "Construction", size: "85 employees", trigger: "Recently opened a second regional office", contact: "Maria Alonso", title: "Director of Finance", phone: "(212) 555-0148", email: "malonso@redlinestructural.com" },
  { company: "Harborview Builders", territory: "New York", industry: "Construction", size: "140 employees", trigger: "Posted 3 AP/finance roles this quarter", contact: "Devon Pratt", title: "CFO", phone: "(315) 555-0122", email: "dpratt@harborviewbuilders.com" },
  { company: "Empire Steel & Concrete", territory: "New York", industry: "Construction", size: "260 employees", trigger: "Won a $40M municipal contract", contact: "Renee Suh", title: "AP Manager", phone: "(716) 555-0193", email: "rsuh@empiresteelconcrete.com" },
  { company: "Sunbelt Fabrication Co.", territory: "Florida", industry: "Manufacturing", size: "190 employees", trigger: "Expanded second shift production", contact: "Carlos Medina", title: "CFO", phone: "(305) 555-0176", email: "cmedina@sunbeltfab.com" },
  { company: "Coastal Precision Parts", territory: "Florida", industry: "Manufacturing", size: "110 employees", trigger: "New ERP rollout announced", contact: "Julia Nance", title: "Director of Finance", phone: "(407) 555-0164", email: "jnance@coastalprecision.com" },
  { company: "Gulfstream Assembly", territory: "Florida", industry: "Manufacturing", size: "310 employees", trigger: "Acquired a smaller competitor", contact: "Marcus Ives", title: "CTO", phone: "(813) 555-0139", email: "mives@gulfstreamassembly.com" },
  { company: "Tidewater Health Partners", territory: "Virginia", industry: "Healthcare", size: "220 employees", trigger: "Opened 2 new outpatient clinics", contact: "Angela Byrd", title: "CEO", phone: "(757) 555-0117", email: "abyrd@tidewaterhealth.com" },
  { company: "Blue Ridge Medical Group", territory: "Virginia", industry: "Healthcare", size: "95 employees", trigger: "Hiring an AP Manager (posted last week)", contact: "Tom Ferris", title: "AP Manager", phone: "(540) 555-0182", email: "tferris@blueridgemed.com" },
  { company: "Piedmont Surgical Associates", territory: "Virginia", industry: "Healthcare", size: "175 employees", trigger: "Switching billing systems this quarter", contact: "Nina Osei", title: "Director of Finance", phone: "(804) 555-0155", email: "nosei@piedmontsurgical.com" },
  { company: "Atlas Site Development", territory: "New York", industry: "Construction", size: "48 employees", trigger: "Landed first contract over $1M", contact: "Greg Halloran", title: "CEO", phone: "(518) 555-0161", email: "ghalloran@atlassitedev.com" },
  { company: "Palm Coast Manufacturing", territory: "Florida", industry: "Manufacturing", size: "230 employees", trigger: "Opened a new production line", contact: "Sara Kim", title: "CFO", phone: "(954) 555-0128", email: "skim@palmcoastmfg.com" },
  { company: "Old Dominion Health Systems", territory: "Virginia", industry: "Healthcare", size: "300 employees", trigger: "Consolidating 3 regional AP teams", contact: "Peter Wallace", title: "CTO", phone: "(703) 555-0149", email: "pwallace@olddominionhealth.com" },
  { company: "Metro Concrete Works", territory: "New York", industry: "Construction", size: "70 employees", trigger: "New leadership hire in finance", contact: "Lauren Diaz", title: "AP Manager", phone: "(646) 555-0187", email: "ldiaz@metroconcrete.com" },
  { company: "Everglades Precision Mfg", territory: "Florida", industry: "Manufacturing", size: "165 employees", trigger: "Flagged for rapid headcount growth", contact: "Brian Cho", title: "Director of Finance", phone: "(561) 555-0173", email: "bcho@evergladesmfg.com" },
  { company: "Commonwealth Care Network", territory: "Virginia", industry: "Healthcare", size: "128 employees", trigger: "Recently changed CFO", contact: "Whitney Marsh", title: "CFO", phone: "(434) 555-0136", email: "wmarsh@commonwealthcare.com" },
  { company: "Hudson Valley Builders", territory: "New York", industry: "Construction", size: "205 employees", trigger: "Expanded into a new county", contact: "Omar Faris", title: "CFO", phone: "(845) 555-0192", email: "ofaris@hudsonvalleybuilders.com" },
];
